projects:
  prismaClient:
    schemaPath: src/schema.graphql
    extensions:
      endpoints:
        default: http://localhost:4000
  prismaServer:
    schemaPath: prisma/datamodel.graphql
    extensions:
      prisma: prisma/prisma.yml